SEVERITY_CRITICAL = "critical"
SEVERITY_HIGH = "high"
SEVERITY_MEDIUM = "medium"
SEVERITY_LOW = "low"
VALID_SEVERITIES = {SEVERITY_CRITICAL, SEVERITY_HIGH, SEVERITY_MEDIUM, SEVERITY_LOW}

INCIDENT_NEW = "new"
INCIDENT_UNDER_REVIEW = "under_review"
INCIDENT_INVESTIGATING = "investigating"
INCIDENT_CONTAINED = "contained"
INCIDENT_RESOLVED = "resolved"
INCIDENT_FALSE_POSITIVE = "false_positive"
VALID_INCIDENT_STATES = {
    INCIDENT_NEW,
    INCIDENT_UNDER_REVIEW,
    INCIDENT_INVESTIGATING,
    INCIDENT_CONTAINED,
    INCIDENT_RESOLVED,
    INCIDENT_FALSE_POSITIVE,
    "New",
    "Under Review",
    "Investigating",
    "Contained",
    "Resolved",
    "False Positive",
}

REVIEW_ATTACK = "attack"
REVIEW_BENIGN = "benign"
REVIEW_FALSE_POSITIVE = "false_positive"
REVIEW_UNCERTAIN = "uncertain"
REVIEW_NOTE = "note"
VALID_REVIEW_VERDICTS = {
    REVIEW_ATTACK,
    REVIEW_BENIGN,
    REVIEW_FALSE_POSITIVE,
    REVIEW_UNCERTAIN,
    REVIEW_NOTE,
}
